# 官方文档
# https://hub.docker.com/r/qq918652593/easy-vdl
# 软件作者：隔壁小王

# easy-vdl 是一款支持多平台（某音、某书、YouTube等）的视频解析与下载的可视化平台。内置智能缓存、批量解析、Emby/Jellyfin 元数据自动生成，界面美观，操作简单，适合个人和媒体库用户

---
version: "3"
# 最后编辑时间：2026-07-04
services:
  easy-vdl:
    image: qq918652593/easy-vdl:latest
    # 镜像地址，仅支持amd64
    container_name: easy-vdl
    # 容器名字
    hostname: easy-vdl
    # 主机名
    volumes:
      - /volume1/downloads/easy-vdl:/app/downloads
      # 视频下载及管理目录，可自定义挂载
      - /volume1/docker/easy-vdl:/app/database
      # 日志目录，建议挂载本地便于排查问题
      - /volume1/docker/easy-vdl:/app/logs
      # 数据库目录，建议挂载本地保证数据持久化
    network_mode: bridge
    # 80端口被占用，不能用host
    ports:
      - 8170:80/tcp
      # WebUI 端口
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
