# 官方文档
# https://github.com/Jeric-X/SyncClipboard
# https://hub.docker.com/r/jericx/syncclipboard-server

# 部署教程
# https://blog.laoda.de/archives/cross-platform-cipboard-syncing-solution

# 剪贴板同步，支持文字、图片和文件。服务器/客户端架构，可以使用客户端内置服务器、独立部署服务器，也可以使用支持WebDAV的网盘作为服务器
# 优化图片类型的剪贴板，功能有：
  # 从任意位置复制图片时，可以直接向文件系统粘贴图片文件，反之亦然
  # 从浏览器复制图片后，后台下载原图到本地，解决无法从浏览器拷贝动态图的问题（大多网站有认证，适用范围有限，支持bilibili动态图片）
  # 从文件系统复制较新格式类型的图片文件时（webp/heic等），在剪贴板内储存gif或jpg格式，用于直接向支持图片的文本框粘贴图片

---
version: "3"
# 最后编辑时间：2026-07-10
services:
  syncclipboard-server:
    image: jericx/syncclipboard-server:latest
    # 镜像地址
    container_name: syncclipboard-server
    # 容器名字
    hostname: syncclipboard-server
    # 主机名
    environment:
      - SYNCCLIPBOARD_USERNAME=user
      - SYNCCLIPBOARD_PASSWORD=password
      # 账号和密码，注意修改
    # network_mode: bridge
    network_mode: host
    # host模式需要容器内的端口不被占用，不需要端口映射，后续端口映射全都开头加#注释掉，否则注释掉这条
    # ports:
      # - 5033:5033/tcp
      # WebUI 端口，其实没必要打开，就是提示你服务正在运行而已
    restart: unless-stopped
    # 重启策略，可根据实际情况而选择 no/always/unless-stopped/on-failure/on-failure:3
    labels:
      icon: http://IP:PORT/i/user_01/syncclipboard_A.png
      # 适用于CasaOS导入时自动写上图标地址
      # 注意：在导入CasaOS时，记得补全本机端口号
      # 注意：图标地址仅供参考，请根据实际填写，推荐自搭建兰空图床使用
      ########################################
      net.unraid.docker.managed: dockerman
      net.unraid.docker.webui: http://[IP]:[PORT:5033]
      # 适用于unraid界面打开WebUI，注意端口号写的是容器端口，如有自定义，自行修改
      net.unraid.docker.icon: /mnt/user/LOGO/syncclipboard.png
      # 适用于unraid的图标，可以写unRAID的路径地址，也可以写一个图标地址(局域网或广域网均可)
      # 注意：通过compose创建的docker容器，无法在unRAID上进行编辑
